name: koode_v2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  record: ^5.1.2
  just_audio: ^0.9.39
  path_provider: ^2.1.4
  path: ^1.9.0
  hive: ^2.2.3
  google_fonts: ^4.0.4
  hive_flutter: ^1.1.0
  animated_background: ^2.0.0

dev_dependencies:
  hive_generator: ^1.0.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/audios/alphabets/


